# Generated by Django 4.2.5 on 2023-09-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer_utilization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('Backend', 'Backend Development'), ('Frontend', 'Frontend Development'), ('Data Science', 'Data Science'), ('Sales', 'Sales')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_member',
        ),
        migrations.CreateModel(
            name='ResourceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer_utilization.resource')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer_utilization.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
