# Generated by Django 4.2.5 on 2023-09-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer_utilization', '0002_technology_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='designation',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Data Analyst', 'Data Analyst'), ('HR', 'Human Resource'), ('CEO', 'Cheif Executive Officer'), ('CTO', 'Cheif Technology Officer'), ('Designer', 'Designer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='skills',
            field=models.TextField(blank=True, choices=[('Management', 'Project Management'), ('ML', 'Machine Learning'), ('Dvelopment', 'Software Devlopment'), ('Hr', 'Human Resource')], null=True),
        ),
    ]
