# Generated by Django 4.2.5 on 2023-11-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engineer_utilization", "0002_status_remove_resource_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="budget_in_dollars",
        ),
        migrations.AlterField(
            model_name="resource",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
