# Generated by Django 4.2.5 on 2023-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer_utilization', '0004_alter_projectresource_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetechnology',
            old_name='experience',
            new_name='experience_in_years',
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='role',
            field=models.CharField(choices=[('Frontend ', 'Frontend Developer'), ('Backend', 'Backend Developer'), ('Devops', 'Devops Developer'), ('Cloud', 'CLoud Architect'), ('Data Science', 'Data Scientist')], max_length=100),
        ),
    ]
