# Generated by Django 4.2.5 on 2023-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer_utilization', '0005_rename_experience_resourcetechnology_experience_in_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='domain',
            field=models.CharField(choices=[('Backend Development', 'Backend Development'), ('Frontend Development', 'Frontend Development'), ('Data Science', 'Data Science'), ('Sales', 'Sales')], max_length=50),
        ),
    ]
