# Generated by Django 4.2.5 on 2023-09-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer_utilization', '0006_alter_technology_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='budget',
            new_name='budget_in_dollars',
        ),
    ]
