# Generated by Django 4.2.5 on 2023-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engineer_utilization", "0007_rename_budget_project_budget_in_dollars"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectresource",
            old_name="resource_joined_date",
            new_name="resource_joined_date_in_project",
        ),
        migrations.AddField(
            model_name="projectresource",
            name="weekly_hour",
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name="resource",
            name="resource_status",
            field=models.CharField(
                choices=[
                    ("Part-Time", "Part Time Employee"),
                    ("Full-Time", "Full Time Employee"),
                    ("Intern", "Internee"),
                ],
                default="Part-Time",
                max_length=50,
            ),
        ),
    ]
