# Generated by Django 4.2.5 on 2023-10-23 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "engineer_utilization",
            "0008_rename_resource_joined_date_projectresource_resource_joined_date_in_project_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectresource",
            old_name="resource_joined_date_in_project",
            new_name="resource_joined_date",
        ),
    ]
