# Generated by Django 4.2.5 on 2023-10-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "engineer_utilization",
            "0009_rename_resource_joined_date_in_project_projectresource_resource_joined_date",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectresource",
            old_name="weekly_hour",
            new_name="allocated_weekly_hour",
        ),
        migrations.AddField(
            model_name="resource",
            name="level",
            field=models.CharField(
                choices=[("1", "Jr. Level"), ("2", "Mid Level"), ("3", "Sr. Level")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resource",
            name="maximum_weekly_hours",
            field=models.IntegerField(default=40),
        ),
    ]
