# Generated by Django 4.2.5 on 2023-09-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_lead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Leads',
        ),
    ]
