# Generated by Django 4.2.5 on 2023-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_leads_created_time_remove_post_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('lost', 'Lost'), ('converted', 'Converted')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='sector',
            field=models.CharField(blank=True, choices=[('Tech', 'Technology'), ('Finance', 'Financial Sector'), ('Health', 'Healthcare')], max_length=100, null=True),
        ),
    ]
