# Generated by Django 4.2.5 on 2023-09-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('outreach_date', models.DateField()),
                ('outreach_method', models.CharField(max_length=50)),
                ('outreach_message', models.TextField()),
                ('response_status', models.CharField(blank=True, choices=[('Positive', 'Positive Response'), ('Negative', 'Negative Response'), ('No', 'No Response')], max_length=50, null=True)),
                ('scheduled_call', models.BooleanField(default=False)),
            ],
        ),
    ]
