# Generated by Django 4.2.5 on 2023-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='response_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive Response'), ('Negative', 'Negative Response'), ('No_Response', 'No Response')], max_length=50, null=True),
        ),
    ]
